template = """
package ${package}.constants;

public class Constants {

    public static final String CREATE = "create/";
    public static final String UPDATE = "update/";
    public static final String DELETE = "delete/";
    public static final String ALL = "all/";
    public static final String BY_ID = "id/";
    public static final String ALL_ACTIVE = "allActive";
    public static final String BY_ROLE = "role/";

    public static final String MST = "MST/";
    public static final String DTL = "DTL/";

    public static final String USER = "user";
    public static final String MODULE = "module";
    public static final String MODULE_WISE = "moduleWise";
    public static final String USER_AUTHORIZATION = "userAuthorization";
    public static final String USER_GROUP = "userGroup";
    public static final String USER_ROLE = "userRole";
    public static final String PRODUCT_CATEGORY = "productCategory";
    public static final String PRODUCT_BRAND = "productBrand";
    public static final String PRODUCT = "product";
    public static final String SYSTEM = "system";
    public static final String CUSTOMER = "customer";
    public static final String CUSTOMER_BRANCH = "customerBranch";
    public static final String CUSTOMER_CONTACT = "customerContact";
    public static final String UPLOAD_FILE = "uploadFile/";

    //Auto Generated By SpringCrudGenerator2.0

    ${vars}
}

"""

static = """
    public static final String ${model.snake.uppper} = "${model.camel}";
"""