template = """
package ${package}.dao;
import ${package}.model.${model};
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.List;
import java.util.Optional;

//Auto Generated By SpringCrudGenerator2.0

public interface ${model}Repository extends JpaRepository<${model}, Long> {
    List<${model}> findByIsActiveTrue();
    Optional<${model}> findByIsActiveTrueAndId(long id);
    List<${model}> findByIsActiveTrueAndId(long id);
}
"""