template = """
package ${package}.services;

import ${package}.dao.${model.cap}Repository;
import com.harvices.getrokdaapi.model.${model.cap};
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.List;

//Auto Generated By SpringCrudGenerator2.0

@Service
public class ${model.cap}Service {
    
    @Autowired
    ${model.cap}Repository repository;

    public List<${model.cap}> getAll() {
        return repository.findAll();
    }

    public List<${model.cap}> getAllActive() {
        return repository.findByIsActiveTrue();
    }

    public ${model.cap} getById(Long id) throws Exception {
        return repository.findById(id).orElseThrow(() -> new Exception("${model.cap} not found"));
    }

    public ${model.cap} getActiveById(Long id) throws Exception {
        return repository.findByIdAndIsActiveTrue(id).orElseThrow(() -> new Exception("${model.cap} not found"));
    }

    public ${model.cap} save(${model.cap} mst) throws Exception {
        return repository.save(mst);
    }

    public ${model.cap} update(${model.cap} mst) throws Exception {
        ${model.cap} existing = getById(id);
        return repository.save(mst);
    }

    public Object delete(Long id) throws Exception {
        ${model.cap} mst = getActiveById(id);
        mst.setActive(false);
        repository.save(mst);
        return new HashMap<>().put("deleted", Boolean.TRUE);
    }
}



"""